name: Build on Push

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

env:
  LATEST_IMG: latest

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag docker.io/ikstream/$IMAGE_NAME:$LATEST_IMG
          docker tag docker.io/ikstream/$IMAGE_NAME:$LATEST_IMG docker.io/ikstream/$IMAGE_NAME:$LATEST_IMG
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image
        run: |
          docker push docker.io/ikstream/$IMAGE_NAME:$LATEST_IMG

